apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: thoaitrands/flask-demo:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "v1.0.0"
        - name: FLASK_ENV
          value: production